version: "3"
services:
  gateway:
    image: caddy:2.4.6-alpine
    ports: 
      - 443:443
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
      - ./webui/dist:/app
      - caddy_data:/data 
      - caddy_config:/config 

  auth:
    build:
      context: ./auth
      args:
        NODE_ENV: production
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
    command: node index.js

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

volumes:
  caddy_data:
    external: true
  caddy_config:
  mongo-db:
    external: true




